### ISSUE TITLE
about the window_Size

### ISSUE THREAD

**Issue by wuyiranhit** [danqu130/Indian_pines_classification#1]
When running the code, I came across a question that when I increase the parameter window_Size even to a very large number, the classification accuracy still do not decrease. Instead, the accuracy increase with the increase of the window_Size, which is abnormal because the IndianPines dataset' spatial resolution is 20m. If the window_Size is too large, the feature extraction process will extract many noise features that do not belong to the center pixel.
So i wonder is there anyone else come across the same problem? 
I would very like to have a discussion with you!

**Comment by danqu130** [comment]
I agree with you that a larger window size introduces more useless data (including the padded zeros and data of other distant objects), and may introduce more noise into the extracted features. But the noise may mainly exist in the features obtained by multi-layer convolutions. It is worth noting that different window sizes are required to retrain different models, so it is possible that the fully connected layer can reduce the effect of noise features and select the useful features for classification by training with a fixed window size. 

In addition, I would like to make one more point. This was a course assignment I did a long time ago, in which I referenced a lot of other opensourced code. I am not sure that random split the training and test sets by pixel position is correct or commonly used. The similarity between the training and test sets may be higher if you set the window size larger, which makes the test set more easily. This may also be one of the reasons for your increased results.

I'm sorry to notice your question so late, I hope my guess can help you. If you have any other questions, welcome to discuss! I will close the issue first.

**Comment by wuyiranhit** [comment]
Thank you very much for your reply. It helps me a lot!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "danqu130/Indian_pines_classification"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月17日(星期五) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [danqu130/Indian_pines_classification] about the window_Size (#1)





 
I agree with you that a larger window size introduces more useless data (including the padded zeros and data of other distant objects), and may introduce more noise into the extracted features. But the noise may mainly exist in the features obtained by multi-layer convolutions. It is worth noting that different window sizes are required to retrain different models, so it is possible that the fully connected layer can reduce the effect of noise features and select the useful features for classification by training with a fixed window size.
 
In addition, I would like to make one more point. This was a course assignment I did a long time ago, in which I referenced a lot of other opensourced code. I am not sure that random split the training and test sets by pixel position is correct or commonly used. The similarity between the training and test sets may be higher if you set the window size larger, which makes the test set more easily. This may also be one of the reasons for your increased results.
 
I'm sorry to notice your question so late, I hope my guess can help you. If you have any other questions, welcome to discuss! I will close the issue first.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
